version: '3.1'

networks:
  newschain:
    external: true

services:

  mongo:
    image: mongo
    restart: always
    container_name: monar2-mongo-db
    volumes:
    - ../mongodata:/data/db
    networks:
      - newschain
    ports:
      - 27017:27017

  s3:
    image: quay.io/minio/minio
    container_name: monar2-minio-mm
    restart: always
    networks:
      - newschain
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ../storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data --console-address ":9001"

  news-chain:
    image: monar2/news-chain
    container_name: news-chain
    restart: always
    networks:
      - newschain
    ports:
      - 8088:8080
    environment:
      MONGO_DB: monar2-mongo-db
      APP_PORT: 8080
      MINIO_SERVER: monar2-minio-mm
      MINIO_PORT: 9000
