version: '3.1'

networks:
  newschain:
    external: true

services:

  mongo:
    image: mongo
    restart: always
    container_name: monar2-mongo-db
    networks:
      - newschain

  news-chain:
    image: monar2/news-chain
    container_name: news-chain
    restart: always
    networks:
      - newschain
    ports:
    - 8080:8080
