version: '3.1'

networks:
  newschain:

services:

  mongo:
    image: mongo
    restart: always
    container_name: monar2-mongo-db
    ports:
      - 27017:27017

  news-chain:
    image: monar2/news-chain
    container_name: news-chain
    restart: always
    ports:
    - 80:8080
