version: '3.1'

networks:
  newschain:
    external: true

services:

  mongo:
    image: mongo
    restart: always
    container_name: monar2-mongo-db
    volumes:
    - ../mongodata:/data/db
    networks:
      - newschain
    ports:
      - 27017:27017

  kong-migrations:
    image: kong
    container_name: kong-proxy-migration
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: monar2-postgres-db
      KONG_PG_PASSWORD: kong
    depends_on:
      - postgres-db
    networks:
      - newschain
    restart: on-failure

  kong-manual:
    image: kong
    container_name: kong-proxy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: monar2-postgres-db
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    depends_on:
      - postgres-db
    networks:
      - newschain
    restart: on-failure
    ports:
    - 80:8000
    - 443:8443
    - 8001:8001
    - 8444:8444

  postgres-db:
    image: postgres
    restart: always
    container_name: monar2-postgres-db
    networks:
      - newschain
    volumes:
      - ../postgresdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
    - 5432:5432



  s3:
    image: quay.io/minio/minio
    container_name: monar2-minio-mm
    restart: always
    networks:
      - newschain
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ../storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data --console-address ":9001"

  news-chain:
    image: monar2/news-chain
    container_name: news-chain
    restart: always
    depends_on:
      - s3
      - mongo
    networks:
      - newschain
    ports:
      - 8088:8080
    environment:
      MONGO_DB: monar2-mongo-db
      APP_PORT: 8080
      MINIO_SERVER: monar2-minio-mm
      MINIO_PORT: 9000
      MINIO_EXTERNAL_SERVER: monar2.jprq.live/minio


