server:
  port: 4444

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      #uri: mongodb+srv://monar2:monar2@cluster0.qzkyt.mongodb.net/news-chain?retryWrites=true&w=majority
      database: news-chain
  application:
    name: "news-chain"



  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
      instance : ${java.rmi.server.hostname}":"${server.port}
    export:
      prometheus:
        enabled: true

  endpoints:
    web:
      exposure:
        include: "*"


